### ISSUE TITLE
Morcoso Code Review

### ISSUE THREAD

**Issue by Manzanas-MarkAngelo** [PUP-BSIT/ex9-digital_dynasty#1]
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html

File names should be in snake case. All lower case.

'Morcos-Daisy.html' should be 'morcos-daisy.html'

Refer to coding guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

___

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html#L35-L36

It is not advisable to use break line statements in html. It is better use proper styling using css.
 
Refer to coding guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

___

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146615624/d29bcdb9-916a-480f-b1c4-3fb27235133d)

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html#L24-L28

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html#L115-L118

Gallery images are not being displayed because linked images are not in the directory. Similarly, the linked html files in "My Works" section is also not in the directory.

___

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html#L60

The header 'Contact Me' is not styled properly because it's outside the container with class 'form'.

___

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/style.css#L26

My interests and hobbies header along with the content inside the container is not styled because of wrong selector name in css file.

___

Suggestions:

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/style.css#L40-L44

If the intent is to style all h2 elements, instead of indicating each h2 class or id, simply selecting h2 will apply the same effect:

```
h2 {
    margin-top: 0;
    background-color: #f5cada;
    padding: 10px;
    border-radius: 5px;
}
```

in this way all h2 elements will be applied with this style.

___

Other content are too close to the edge of the page. An example is the testimonials, the reader would have to look from the left most side of the page all the way to the right most side to read the content. Adding margins to your webpage containers will make it more readable and will improve user experience.

The headers are not aligned properly,

___

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146615624/d5934663-7054-4fed-b4fb-1394657a75ed)

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Morcoso_Daisy/Morcos-Daisy.html#L35-L55

The content under testimonials is not readable especially in mobile view. Consider adding margins to the <p> elements under testimonials.

___

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146615624/529780a8-ccf7-406a-88e7-0cc2c347dff1)

The hyperlink references under "My Works" container does not look clickable. It is possible to style them and make them appear as something the user can interact with which will improve system navigation.

Example button styling for anchor elements:

```
/* Style anchor elements within the works list */
.works ol li a {
    display: inline-block;
    padding: 10px 30px; /* Adjust padding for desired button size */
    text-decoration: none;
    color: #ffffff;
    background-color: #60102a;
    border: 2px solid transparent;
    border-radius: 25px; /* Use half of the button height for rounded corners */
    transition: all 0.3s ease; /* Smooth transition for hover effect */
    text-align: center;
    width: 200px; /* Set a fixed width for consistent button size */
    box-sizing: border-box; /* Include padding and border in the width calculation */
}

/* Hover effect for anchor elements */
.works ol li a:hover {
    background-color: #8c1d41; /* Change background color on hover */
    border-color: #8c1d41; /* Change border color on hover */
}
    background-color: #813d54;
    border-color: #813d54;
}
```
- note that this is just an example and there are other methods to make it look interactable.

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146615624/6b81bd2c-1cec-4e43-906c-f550d9ae320b)

**Comment by Morcoso-daisy** [comment]
Thank you!
