### ISSUE TITLE
Norona Code Review

### ISSUE THREAD

**Issue by Malaluan-KylaRica** [PUP-BSIT/ex9-digital_dynasty#2]
![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600161/a493383b-45a2-4a7e-a3ac-bb11977c1d70)
--> Kindly remove these unnecessary files because they are not needed for this exercise.
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR39DiTwf5pF_mf-9x8C63cMzuXkd8kMvdEVM5scAuOpT7lHkVKgxCq8sjE#slide=id.g25d18931cb7_3_0

<hr>

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/norona_marynicole/index.html#L78

--> You can remove the unnecessary breaking of lines, and place it in the proper position.
--> reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR39DiTwf5pF_mf-9x8C63cMzuXkd8kMvdEVM5scAuOpT7lHkVKgxCq8sjE#slide=id.g29e6ce31160_0_27

<hr>

**Suggestions:**

--> For your gallery, I suggest putting your picture from below in the empty space on the first row so all the pictures can fit in just one row.
--> like these: (this is just a reference/example, it still depends on you on how you would modify your code)

> .gallery {
  text-align: center;
}

>.gallery img {
  width: calc(100% / 6 - 10px); /* Adjust the width to fit 6 images in a row with a small gap */
  height: auto;
  border: 2px solid rgb(189, 45, 122);
  margin: 5px; /* Add a small margin for spacing between images */
}

<hr>

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600161/a7417cb4-1a5d-4a44-b6fa-1a60b207c57a)
-->I saw that in the full name input field, the field (box) is bold even when it's not selected. If it doesn't need to be bold, I suggest it should look also like the other fields. It should only become bold when the user selected it, to also avoid confusion.
<hr>

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600161/75756609-7d9e-48cb-a5dc-562f0b355ac4)
--> In the testimonial content, you can add bullet points or numbering to emphasize that they are different and not just one paragraph.
--> You can use the list tags like this:

> <p>
        <li>I couldn't ask for better group mate in coding. Her commitment to
        teamwork and willingness to lend a hand whenever needed have been
        instrumental in our success. -Bergado, Shamma</li>
<hr>

![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600161/d410ef14-15b2-4404-8424-a1812434223b)
--> you can also add some styling in your FORM class.
--> it can be a style for the submit button or in the form content. 
--> you can change "Message" to "Write a Message" to better understand the use of the textarea
--> you can make it like this or even better
![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600161/f995e25e-f2f8-48d0-8aa5-2a92c10c0493)

<hr>

--> Lastly, this is just my suggestion. You can separate different contents into different classes, such as gallery, form, testimonials, my works, and my interests and hobbies. This way, when it comes to styling, it will be easier for you to design the target content you want to focus on without affecting the others.

**Comment by norona-marynicole** [comment]
Thank you po.

**Comment by norona-marynicole** [comment]
Thank you so much po.
