### ISSUE TITLE
Reyes, John Ruiz Code Review

### ISSUE THREAD

**Issue by Sanchez-SamanthaNicole** [PUP-BSIT/ex9-digital_dynasty#3]
**Incorrect Pathing:**

- The href attributes in the anchor tags are pointing to paths that don't match the actual file structure. 

- The folder name specified in the href attributes is 'works', while it should be 'work' based on your folder in the directory.

- The file names specified in the href attributes do not match the actual file names.

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/index.html#L29
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/index.html#L30
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/index.html#L31
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/index.html#L32
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/index.html#L33

**Recommendations:**

**Update Hyperlink Paths:**

- Modify the href attributes to reflect the updated directory structure and file names.

**Standardize File Naming:**

- Ensure consistency in file naming conventions for better readability.

<hr>

**Remove unnecessary comments in your css file.**

https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L100
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L101
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L102
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L103
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L105
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L109
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L130
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L131
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L132
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L141
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L142
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L144
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_JohnRuiz/style.css#L145

**Refer to coding guidelines:** https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by REYESJOHNRUIZ** [comment]
Thank you po
