### ISSUE TITLE
Reyes, Paul Code Review

### ISSUE THREAD

**Issue by Rasquero-ViaClariz** [PUP-BSIT/ex9-digital_dynasty#4]
@Reyes-PaulAngelo 

- I'm glad to see that you've followed the coding guidelines well, with minimal deviations.
**Suggestion:** consider adding spaces in between different parts of your code to make it look more organized. 
**Example:**
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Reyes_PaulAngelo/index.html#L72-L102

**you can make it like this:**
![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146600112/890f4b49-b731-4e57-a86e-19f70155eafe)

**Quick Note:** regarding to the contact form on your website. It's awesome to see that it's responsive, allowing for a seamless experience across different devices. However, I noticed that when the size is being adjusted or when it's made responsive, there seems to be a bit of a glitch with the positioning of the text, text fields, and submit button. It appears that they're not sticking to their intended positions when responsiveness is applied. 

**Suggestion:**  
 - Review and adjust the positioning properties in your css file applied to form elements to ensure they adapt well to different screen sizes.
 - Check and refine the grid template areas and other grid-related styling within the media queries to ensure consistency and responsiveness across various devices.
 - Test the website thoroughly on different devices and screen sizes to identify and fix any remaining layout glitches.

- I also noticed a minor styling detail in your code that might contribute to the lack of spacing in the contact form and gallery sections. It appears that margins haven't been explicitly defined for these elements.

**Comment by Reyes-PaulAngelo** [comment]
Thank you
