### ISSUE TITLE
Bergado, Shamma Code Review

### ISSUE THREAD

**Issue by Asebuque-ChrystineNoelle** [PUP-BSIT/ex9-digital_dynasty#5]
### Output Review

1.  Whitespace Overuse
         The output design appears cluttered due to excessive whitespace between elements.
![Screenshot 2024-04-16 221528](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146621536/3881c57d-57ab-46cb-85b7-8c7d7e7d8d27)

2. Lack of Responsiveness
          The website design lacks responsiveness, posing usability issues across different devices.
![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146621536/33f886aa-0db5-4f10-a390-f0795699b1b2)

#

### HTML Review

1.  All files should be named in snake case, all lower case.
 ![image](https://github.com/PUP-BSIT/ex9-digital_dynasty/assets/146621536/845f23fe-8221-4d90-90bd-8f8d634f0623)
See Coding Guidelines: 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0
#

2.  Avoid using `<b>` in HTML for bold text. It's better to use CSS for styling to maintain semantic clarity.
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L19
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L25
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L36
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L45
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L53
See Reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element#inline_text_semantics
#

3. Links should be formatted to appear in one line for improved readability. Allowed to exceed the 80-column
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L16-L18
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L32-L35
https://github.com/PUP-BSIT/ex9-digital_dynasty/blob/dd3048455cb6cb0e1c05de7d505b1a6755a150a5/Bergado_Shamma/index.html#L41-L44
See Coding Guidelines:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

**Comment by bergado-shamma** [comment]
Thank you po
